### ISSUE TITLE
Editar Perfil de Usuario - No guarda cambios

### ISSUE THREAD

**Issue by CarlosDaniel661** [igrowker/i004-reffindr-front#167]
Editar perfil de usuario, no guarda los cambios, muestra mensaje de aceptación, pero los cambios no se ven reflejados.

![Image](https://github.com/user-attachments/assets/d02fdf75-0bb8-4f72-a869-1e267f5c9edc)

**Comment by JoaquinFeola** [comment]
Hola carlos como estas buenas noches, dale genial ahora lo arreglo !
