### ISSUE TITLE
Componentes de boton reutilizable

### ISSUE THREAD

**Issue by JoaquinFeola** [igrowker/i004-reffindr-front#24]
Crear componente de botón reutilizable. 
Deberás analizar cuales son los botones que se repiten y crear un componente para ese boton, si hay mas de un estilo de boton crear otro componente siguiendo la arquitectura planteada en el proyecto.

Cosas a tener en cuenta:
- Quiero poder utilizar cualquier atributo del elemento boton en este componente eso significa recibir por props cada uno de los atributos inherentes al boton.
- Pensar en donde iria ubicado este componente (es un componente que se va a utilizar a lo largo de toda la aplicación)
- Crear una carpeta dedicada a botones
- Trabajamos siempre en inglés para cumplir con las mejores prácticas

**Comment by EstreFlores** [comment]
okey, muchas gracias.
