### ISSUE TITLE
Crear view de "mis anuncios" en la pagina de perfil del inquilino

### ISSUE THREAD

**Issue by JoaquinFeola** [igrowker/i004-reffindr-front#76]
![image](https://github.com/user-attachments/assets/855f570b-cc12-4611-a727-9f3fb5dc6736)

**Comment by CarlosDaniel661** [comment]
La página se visualiza con las distintas publicaciones, pero no cargan las imágenes de previsualización y se demora hasta 8 seg en completar la carga

![Image](https://github.com/user-attachments/assets/4069f906-bf52-4a1d-84da-57307b32f8a5)

@j0sep0z0 @JoaquinFeola

**Comment by JoaquinFeola** [comment]
Hola @CarlosDaniel661 las imagenes no cargan porque no tenemos pero la demora de 8segs es por la velocidad de la API, igual estamos trabajando tambien para que el front vaya lo mas ligero posible!! entre hoy y mañana vas a ver que va a mejorar mucho la performance
